/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export function FaceTwo(props) {
    const { nodes, materials } = useGLTF("/face2.glb");
    return (
        <group {...props} dispose={null} scale={2} position={[0,0,0]}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.box_001.geometry}
                material={materials["Material.013"]}
                position={[-0.322, -0.038, -0.497]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.125}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.box_001001.geometry}
                material={materials["Material.013"]}
                position={[-0.268, -0.036, -0.497]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.077}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.fir_001.geometry}
                material={materials["Material.010"]}
                position={[0.326, -0.146, -0.497]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.063}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.fir_001001.geometry}
                material={materials["Material.010"]}
                position={[0.326, 0.018, -0.497]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.063}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.fir_001002.geometry}
                material={materials["Material.010"]}
                position={[0.166, -0.093, -0.5]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.063}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.log_001.geometry}
                material={materials["Material.012"]}
                position={[-0.291, -0.234, -0.499]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.092}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.pointer_001.geometry}
                material={materials["Material.011"]}
                position={[-0.085, 0.157, -0.501]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.093}
            />
        </group>
    );
}

useGLTF.preload("/face2.glb");