/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export function FaceThree(props) {
    const { nodes, materials } = useGLTF("/face3.glb");
    return (
        <group {...props} dispose={null} scale={2}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.big_fabulous_tree_001.geometry}
                material={materials["Material.014"]}
                position={[-0.307, -0.497, -0.345]}
                rotation={[Math.PI, 0, 0]}
                scale={0.039}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.fabulous_mushroom_001.geometry}
                material={materials["Material.016"]}
                position={[0.259, -0.496, -0.276]}
                rotation={[Math.PI, 0, 0]}
                scale={0.137}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.fabulous_mushroom_003.geometry}
                material={materials["Material.016"]}
                position={[0.384, -0.497, 0.322]}
                rotation={[Math.PI, 0, 0]}
                scale={0.137}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.fabulous_mushroom_004.geometry}
                material={materials["Material.015"]}
                position={[0.158, -0.502, 0.047]}
                rotation={[Math.PI, 0, 0]}
                scale={0.025}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.fabulous_mushroom_004001.geometry}
                material={materials["Material.015"]}
                position={[0.233, -0.501, 0.064]}
                rotation={[Math.PI, 1.361, 0]}
                scale={0.025}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.fabulous_mushroom_004002.geometry}
                material={materials["Material.015"]}
                position={[0.177, -0.492, 0.115]}
                rotation={[Math.PI, 1.361, 0]}
                scale={0.049}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.house_001.geometry}
                material={materials["Material.017"]}
                position={[-0.258, -0.5, 0.269]}
                rotation={[Math.PI, -Math.PI / 4, 0]}
                scale={0.106}
            />
        </group>
    );
}

useGLTF.preload("/face3.glb");