/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export function FaceOne(props) {
    const { nodes, materials } = useGLTF("/face1.glb");
    return (
        <group {...props} dispose={null} position={[0,0,0]} scale={2}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.cart_001.geometry}
                material={materials["Material.009"]}
                position={[-0.322, 0.497, 0.217]}
                rotation={[0, 0.209, 0]}
                scale={0.092}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.stall_001.geometry}
                material={materials["Material.008"]}
                position={[0.226, 0.498, 0.27]}
                scale={0.085}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.tree_001.geometry}
                material={materials["Material.005"]}
                position={[0.284, 0.5, -0.176]}
                scale={0.041}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.tree_001001.geometry}
                material={materials["Material.005"]}
                position={[-0.301, 0.5, -0.174]}
                rotation={[0, 0.436, 0]}
                scale={0.041}
            />
        </group>
    );
}

useGLTF.preload("/face1.glb");

